const URL = "http://localhost:5001";
// const URL = "http://localhost/DACN1_API/api";

export default {
    URL_getProduct: URL + "/product/get-all/1",
    URL_getCategory: URL + "/category/get-list",
    URL_getProductCategory: URL + "/getProductCategory.php",
    URL_getProductDetail: URL + "/product/detail",
    URL_getProductRelated: URL + "/getProductRelated.php",
    URL_searchProduct: URL + "/product/get-all/1",
    URL_getInformation: URL + "/getInformation.php",
    URL_getProductCategory: URL + "/getProductCategory.php",
    URL_updateCart: URL + "/cart/update-quantity-cart",
    URL_deleteCart: URL + "/cart/remove-product-cart",
    URL_getCart: URL + "/cart/get-cart-by-idUser/",
    URL_setCart: URL + "/cart/add-new",
    URL_setOrder: URL + "/setOrder.php",
    URL_setNewPass: URL + "/setNewPass.php",
    URL_setNewUser: URL + "/user/register",
    URL_setViewProduct: URL + "/setViewProduct.php",
    URL_getUser: URL + "/user/login-user",
    URL_getDetailOrder: URL + "/getDetailOrder.php",
    URL_getClientOrder: URL + "/getClientOrder.php",
    URL_getOrderByUser: URL + "/getOrderByUser.php",
    URL_getHomeAdmin: URL + "/getHomeAdmin.php",
    URL_getOrder: URL + "/getOrder.php",
    URL_getIdAdmin: URL + "/getIdAdmin.php",
    URL_getUserAdmin: URL + "/getUserAdmin.php",
    URL_deleteUser: URL + "/deleteUser.php",
    URL_editRole: URL + "/editRole.php",
    URL_addNewProduct: URL + "/product/add-new",
    URL_deleteProduct: URL + "/deleteProduct.php",
    URL_deleteOrder: URL + "/deleteOrder.php",
    URL_editStatus: URL + "/editStatus.php",
    URL_addNewCategory: URL + "/category/add-new",
    URL_deleteCategory: URL + "/deleteCategory.php",
    URL_editCategory: URL + "/editCategory.php",
    URL_getCategoryEdit: URL + "/getCategoryEdit.php",
    URL_editProduct: URL + "/editProduct.php",
    URL_getTopProduct: URL + "/product/get-all/1",
    URL_getNewProduct: URL + "/getNewProduct.php",
    URL_setInfor: URL + "/user/update-user",

    // setInfor.php
};
